{
 "title": "Translations  Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Latency alerts", "type": "alertlist", "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage %",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 0 },
   "targets": [
    {
     "expr": "topk(3, sum by (instance) (rate(process_cpu_usage[5m])))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total translations",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 10, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(http_client_requests_seconds_count{status=\"200\"})",
     "legendFormat": "Translations"
    },
    {
     "expr": "sum(http_client_requests_seconds_count{status=\"400\"})",
     "legendFormat": "Failed Translations"
    }
   ]
  },
  {
   "title": "Spanish ",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by (instance) (spanish_requests_latency_seconds_count{instance=\"spanish-processor:8082\"})",
     "legendFormat": "Translations"
    }
   ]
  },
  {
   "title": "Failed Spanish",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 4, "y": 5 },
   "targets": [
    {
     "expr": "((sum by (instance) (spring_kafka_listener_seconds_count{instance=\"spanish-processor:8082\"})) - (sum by (instance) (spanish_requests_latency_seconds_count{instance=\"spanish-processor:8082\"}))) / (sum by (instance) (spanish_requests_latency_seconds_count{instance=\"spanish-processor:8082\"}))",
     "legendFormat": "Translations"
    }
   ]
  },
  {
   "title": "Spanish translations latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 7, "y": 5 },
   "yaxes": [
    { "format": "short", "label": "seconds" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, rate(spanish_requests_latency_seconds_bucket[5m])) > 0.01",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Italian",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum by (instance) (italian_requests_latency_seconds_count{instance=\"italian-processor:8083\"})",
     "legendFormat": "Translations"
    }
   ]
  },
  {
   "title": "Failed Italian",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 4, "y": 11 },
   "targets": [
    {
     "expr": "((sum by (instance) (spring_kafka_listener_seconds_count{instance=\"italian-processor:8083\"})) - (sum by (instance) (italian_requests_latency_seconds_count{instance=\"italian-processor:8083\"}))) / (sum by (instance) (italian_requests_latency_seconds_count{instance=\"italian-processor:8083\"}))",
     "legendFormat": "Translations"
    }
   ]
  },
  {
   "title": "Italian translations latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 7, "y": 11 },
   "yaxes": [
    { "format": "short", "label": "seconds" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, rate(italian_requests_latency_seconds_bucket[5m])) > 0.01",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "German",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum by (instance) (german_requests_latency_seconds_count{instance=\"german-processor:8084\"})",
     "legendFormat": "Translations"
    }
   ]
  },
  {
   "title": "Failed German",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 4, "y": 17 },
   "targets": [
    {
     "expr": "((sum by (instance) (spring_kafka_listener_seconds_count{instance=\"german-processor:8084\"})) - (sum by (instance) (german_requests_latency_seconds_count{instance=\"german-processor:8084\"}))) / (sum by (instance) (german_requests_latency_seconds_count{instance=\"german-processor:8084\"}))",
     "legendFormat": "Translations"
    }
   ]
  },
  {
   "title": "German translations latency",
   "type": "graph",
   "gridPos": { "h": 5, "w": 9, "x": 7, "y": 17 },
   "yaxes": [
    { "format": "short", "label": "seconds" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, rate(german_requests_latency_seconds_bucket[5m])) > 0.01",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } }
 ]
}